version: '3.7'

services:
  planet-learning-database:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: learning
      POSTGRES_USER: planet
      POSTGRES_DB: planet-learning-postgresql
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - /planet-learning/postgres-data:/var/lib/postgresql/data
  planet-learning-tensorboard:
    build:
      context: ./
      dockerfile: ./docker/tensorboard/Dockerfile
    ports:
      - 6006:6006
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: ./
        target: /planet-learning
  planet-learning-code:
    build:
      context: ./
      dockerfile: ./docker/code/Dockerfile
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: ./
        target: /planet-learning/code
      - type: volume
        source: data
        target: ${DATA_ROOT}
    depends_on:
      - planet-learning-database

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_IP}       # IP of nfs server.  This is also where you put any options '-o' in standard option format
      device: :${NFS_TARGET}  # location on nfs server of file/dir you want to mount