version: '3.4'

services:
  planet-learning-tensorboard:
    build:
      context: ./
      dockerfile: ./docker/tensorboard/Dockerfile
    ports:
      - 6006:6006
    volumes:
      - type: bind
        source: ./
        target: /planet-learning
  planet-learning-code:
    build:
      context: ./
      dockerfile: ./docker/code/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /planet-learning
  planet-learning-database:
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: learning
      POSTGRES_USER: planet
      POSTGRES_DB: planet-learning-postgresql
