version: '3.4'

services:
  planet-learning-database:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: learning
      POSTGRES_USER: planet
      POSTGRES_DB: planet-learning-postgresql
  
  planet-learning-tensorboard:
    build:
      context: ./
      dockerfile: ./docker/tensorboard/Dockerfile
    ports:
      - 6006:6006
    volumes:
      - type: bind
        source: ./
        target: /planet-learning
  
  planet-learning-code:
    build:
      context: ./
      dockerfile: ./docker/code/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /planet-learning/code
      - type: bind
        source: /nfs/planet-learning
        target: /planet-learning/data
    depends_on:
      - planet-learning-database
