# Launches a database docker
# Please change this line if using another custom image of Tensorflow you built
FROM postgres

LABEL Name=planet-learning-database Version=0.0.1

#setting the working directory
WORKDIR /planet-learning